name: Deploy to EC2

on:
  push:
    branches: [ "pipeline" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/job-scraper/gigs-tech-scraping
            git pull origin pipeline
            source venv/bin/activate
            #pip install -r requirements.txt
