name: Scrape Jobs

on:
  schedule:
    # - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
    - cron: '40 20 * * *'  # Runs every day at 8:40 PM UTC (9:40 PM WAT)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # python-version: '3.10'
          python-version: '3.12'


      - name: Export environment variables
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
          PROVIDER: ${{ secrets.PROVIDER }}

          HOST: ${{ secrets.HOST }}
          DATABASE: ${{ secrets.DATABASE }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}

          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: echo "Environment variables set"
        run: echo "keys env: ${{ env.OPENAI_API_KEY }}, secret:${{ secrets.PROVIDER }}"

      - name: Install dependencies and run scraper
        run: |
          pip install -r requirements.txt
          python main.py